defaults:
  - model: mlp_classifier
  - inference : mcmc
  - data : mnist
  - trainer : default
  - _self_

hydra:
  run:
    dir: experiment_results/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
      dir: experiment_results/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
      subdir: ${hydra.job.num}
