defaults:
  - model: "???"
  - inference: "???"
  - data: "???"
  - trainer: no_checkpoints
  - optuna/search_space: "???"
  - hydra: sweep
  - _self_

study_storage_file_name: optuna.db

monitor: "err/val"

optuna_callback:
  _target_: optuna.integration.PyTorchLightningPruningCallback
  monitor: ${monitor}

study:
  _target_: optuna.create_study
  study_name: ???
  load_if_exists: true
  pruner:
    _target_: optuna.pruners.NopPruner

trainer:
  progress_bar_refresh_rate: 0

optimize_args:
  n_trials: 100

seed : 123
