defaults:
  - model: "???"
  - inference: "???"
  - data: "???"
  - trainer: no_checkpoints
  - hydra: sweep
  - sweep/search_space: "???"
  - sweep/sampler: tpe
  - sweep/study/pruner: nop
  - sweep/study: sqlite
  - _self_

sweep:

  study_storage_file_name: optuna.db
  study_name: "???"

  study:
    _target_: optuna.create_study
    study_name: ${sweep.study_name}
    load_if_exists: true

  monitor: "err/val"

  optimize_args:
    n_trials: 200

optuna_callback:
  _target_: optuna.integration.PyTorchLightningPruningCallback
  monitor: ${sweep.monitor}

trainer:
  progress_bar_refresh_rate: 0

seed : 123
