experiment_name: sghmc_gradients

run_dir: experiment_results/${latest_run_dir:${experiment_name}}
out_dir: ${run_dir}/_plots_

run:
  _target_: src.experiments.common.get_run_from_path
  path: ${run_dir}

hydra:
  run:
    dir: ${out_dir}
  sweep:
    dir: ${out_dir}
    subdir: ${hydra.job.num}
