defaults:
  - /sampler@_group_ : sghmc
  - /sample_container@_group_ : fifo

_target_: src.inference.mcmc.MCMCInference
model : ${model}
sampler : ${sampler}
sample_container : ${sample_container}
burn_in: 50mo