defaults:
  - prior_config: scale_mixture

_target_: src.inference.vi.VariationalInference
model : ${model}
lr : 0.001
n_particles : 10
kl_weighting_scheme:
  _target_: 'src.inference.vi.ConstantKLWeight'
