defaults:
  - prior_spec: normal_mixture

_target_: src.inference.vi.VariationalInference
model : ${model}
lr : 0.001
n_samples : 10
kl_weighting_scheme:
  _target_: 'src.inference.vi.ConstantKLWeight'
