_target_: pytorch_lightning.trainer.Trainer

logger:
  _target_: src.experiments.common.FlatTensorBoardLogger
  save_dir: "./metrics"
  default_hp_metric: False

callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: "./checkpoints"
  - _target_: src.utils.SilenceWarnings
