_target_: pytorch_lightning.trainer.Trainer

logger:
  _target_: src.experiments.common.FlatTensorBoardLogger
  save_dir: "./metrics"

callbacks:
  _target_: src.experiments.common.default_callbacks


